<a href="https://colab.research.google.com/github/olumorothy/pytorch_projects/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.3.0+cu121


Creating Tensors
Pytorch tensors are created using torch.tensor() = https://pytorch.org/docs/stable/tensors.html

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim #nos of dimensions of a scalar

0

In [5]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape #2 by 1 element

torch.Size([2])

In [8]:
#Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0]

tensor([7, 8])

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# TENSOR
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

### Random Tensors

Random tensors are important because the way neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [17]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3392, 0.0687, 0.6253, 0.1908],
        [0.7727, 0.7307, 0.8312, 0.4739],
        [0.6054, 0.2423, 0.1909, 0.4610]])

In [18]:
random_tensor.ndim

2

In [19]:
#create a random tensor with simialr shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channnel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)